- name: configure frontend server
  hosts: frontend
  become: yes

  tasks:
    - name: install nginx server
      ansible.builtin.dnf:
        name: nginx
        state: latest
    - name: start and enable nginx
      ansible.builtin.dnf:
        name: nginx
        state: started
        enabled: yes
    - name: delete default website
      ansible.builtin.file:
        path: /usr/share/nginx/html
        state: absent
    - name: create a html directory
      ansible.builtin.file:
        path: /usr/share/nginx/html
        state: directory
    - name: download and extract front end code
      ansible.builtin.unarchive:
        src: https://expense-builds.s3.us-east-1.amazonaws.com/expense-frontend-v2.zip
        dest: /usr/share/nginx/html
        remote_src: yes
    - name: copy bakent conferation
      ansivle.builtin.copy:
        src: expense.conf
        dest: /etc/nginx/default.d/expense.conf
    - name: restart nginx
      ansible.builtin.service:
        name: nginx
        state: restarted
